[[redirects]]
  from = "/categories"
  to = "https://moon-backend.afkborn.keenetic.pro/categories"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/products"
  to = "https://moon-backend.afkborn.keenetic.pro/products"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/products/"
  to = "https://moon-backend.afkborn.keenetic.pro/products/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
