//categoryActions
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

//productActions
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";